import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About Us - Roadvize",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-16">
      <h1 className="text-3xl font-bold text-gray-800 mb-8">About Us</h1>
      <p className="text-gray-600 mb-4">
        Welcome to QuickRide Taxi, your trusted partner for safe and reliable
        transportation across India. With a mission to provide exceptional
        service, we ensure that every ride is comfortable and hassle-free.
      </p>
      <p className="text-gray-600 mb-4">
        Our drivers are experienced, vetted, and committed to your safety. We
        use the latest technology to provide real-time tracking and secure
        payment options, making your travel experience as smooth as possible.
      </p>
      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        Our Values
      </h2>
      <ul className="list-disc pl-5 text-gray-600">
        <li>Safety: Your safety is our top priority.</li>
        <li>
          Reliability: Count on us to get you to your destination on time.
        </li>
        <li>Affordability: Enjoy competitive pricing for quality service.</li>
        <li>
          Customer Satisfaction: We value your feedback and strive for
          excellence.
        </li>
      </ul>
    </div>
  );
}
