import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Roadvize",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-16">
      <h1 className="text-3xl font-bold text-gray-800 mb-6">Privacy Policy</h1>
      <p className="text-gray-600 mb-4">Last updated: [Insert Date]</p>
      <p className="mb-4">
        At QuickRide Taxi, we value your privacy. This Privacy Policy outlines
        how we collect, use, and protect your information when you use our
        services.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        1. Information We Collect
      </h2>
      <ul className="list-disc ml-5 text-gray-600 mb-4">
        <li>Personal Information: Name, email address, phone number, etc.</li>
        <li>Location Data: Pickup and drop-off locations.</li>
        <li>
          Payment Information: Credit/debit card details (processed through a
          secure payment gateway).
        </li>
        <li>Usage Data: Information about how you use our app and services.</li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        2. How We Use Your Information
      </h2>
      <p className="text-gray-600 mb-4">
        We may use the information we collect for various purposes, including:
      </p>
      <ul className="list-disc ml-5 text-gray-600 mb-4">
        <li>To provide and maintain our services.</li>
        <li>To process your bookings and payments.</li>
        <li>To improve our app and services.</li>
        <li>To communicate with you regarding your bookings.</li>
        <li>To monitor the usage of our services.</li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        3. Sharing Your Information
      </h2>
      <p className="text-gray-600 mb-4">
        We do not sell or rent your personal information to third parties. We
        may share your information in the following situations:
      </p>
      <ul className="list-disc ml-5 text-gray-600 mb-4">
        <li>With service providers to facilitate our services.</li>
        <li>To comply with legal obligations.</li>
        <li>To protect and defend our rights or property.</li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        4. Data Security
      </h2>
      <p className="text-gray-600 mb-4">
        We take the security of your data seriously and implement various
        measures to protect your personal information. However, no method of
        transmission over the Internet or electronic storage is 100% secure.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        5. Your Rights
      </h2>
      <p className="text-gray-600 mb-4">
        Depending on your location, you may have certain rights regarding your
        personal information, including the right to:
      </p>
      <ul className="list-disc ml-5 text-gray-600 mb-4">
        <li>Access your personal data.</li>
        <li>Request correction of your personal data.</li>
        <li>Request deletion of your personal data.</li>
        <li>Object to processing your personal data.</li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        6. Changes to This Privacy Policy
      </h2>
      <p className="text-gray-600 mb-4">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
        7. Contact Us
      </h2>
      <p className="text-gray-600 mb-4">
        If you have any questions about this Privacy Policy, please contact us
        at:
      </p>
      <p className="text-gray-600 mb-4">Email: support@quickride.com</p>
      <p className="text-gray-600 mb-4">Phone: +1 (123) 456-7890</p>
    </div>
  );
}
