import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Contact Us - Roadvize",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-16">
      <h1 className="text-3xl font-bold text-gray-800 mb-8">Contact Us</h1>
      <form className="space-y-4">
        <div>
          <label className="block text-gray-700" htmlFor="name">
            Name
          </label>
          <input
            type="text"
            name="name"
            required
            className="w-full p-2 border border-gray-300 rounded-md"
          />
        </div>
        <div>
          <label className="block text-gray-700" htmlFor="email">
            Email
          </label>
          <input
            type="email"
            name="email"
            required
            className="w-full p-2 border border-gray-300 rounded-md"
          />
        </div>
        <div>
          <label className="block text-gray-700" htmlFor="message">
            Message
          </label>
          <textarea
            name="message"
            required
            rows={4}
            className="w-full p-2 border border-gray-300 rounded-md"
          />
        </div>
        <button
          type="submit"
          className="bg-yellow-500 text-white px-4 py-2 rounded-md hover:bg-yellow-600"
        >
          Send Message
        </button>
      </form>
    </div>
  );
}
