import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
// import OfferBar from "@/components/OfferBar/OfferBar";

export const metadata: Metadata = {
  title: "Roadvize - Taxi Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <OfferBar /> */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
