import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Services - Roadvize",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-16">
      <h1 className="text-3xl font-bold text-gray-800 mb-8">Our Services</h1>
      <p className="text-gray-600 mb-4">
        At QuickRide Taxi, we offer a range of services to cater to your
        transportation needs:
      </p>
      <ul className="list-disc pl-5 text-gray-600">
        <li className="mb-2">
          <strong>Local Rides:</strong> Reliable transportation for your daily
          commutes and errands.
        </li>
        <li className="mb-2">
          <strong>Airport Transfers:</strong> Hassle-free rides to and from the
          airport, available 24/7.
        </li>
        <li className="mb-2">
          <strong>Outstation Trips:</strong> Enjoy long-distance travel with our
          comfortable vehicles.
        </li>
        <li className="mb-2">
          <strong>Corporate Services:</strong> Customized transportation
          solutions for businesses and events.
        </li>
      </ul>
      <p className="text-gray-600 mt-4">
        No matter where you need to go, our dedicated team is here to provide a
        seamless travel experience.
      </p>
    </div>
  );
}
