import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Blogs - Roadvize",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <h1 className="flex items-center justify-center">READ BLOGS</h1>
    </div>
  );
}
